# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mage/RawData

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mage/RawData

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mage/RawData/CMakeFiles /home/mage/RawData/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mage/RawData/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PmtData

# Build rule for target.
PmtData: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PmtData
.PHONY : PmtData

# fast build rule for target.
PmtData/fast:
	$(MAKE) -f CMakeFiles/PmtData.dir/build.make CMakeFiles/PmtData.dir/build
.PHONY : PmtData/fast

#=============================================================================
# Target rules for targets named PmtData_static

# Build rule for target.
PmtData_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 PmtData_static
.PHONY : PmtData_static

# fast build rule for target.
PmtData_static/fast:
	$(MAKE) -f CMakeFiles/PmtData_static.dir/build.make CMakeFiles/PmtData_static.dir/build
.PHONY : PmtData_static/fast

#=============================================================================
# Target rules for targets named RawData

# Build rule for target.
RawData: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RawData
.PHONY : RawData

# fast build rule for target.
RawData/fast:
	$(MAKE) -f CMakeFiles/RawData.dir/build.make CMakeFiles/RawData.dir/build
.PHONY : RawData/fast

#=============================================================================
# Target rules for targets named RawData_static

# Build rule for target.
RawData_static: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RawData_static
.PHONY : RawData_static

# fast build rule for target.
RawData_static/fast:
	$(MAKE) -f CMakeFiles/RawData_static.dir/build.make CMakeFiles/RawData_static.dir/build
.PHONY : RawData_static/fast

PmtData.o: PmtData.cpp.o
.PHONY : PmtData.o

# target to build an object file
PmtData.cpp.o:
	$(MAKE) -f CMakeFiles/PmtData_static.dir/build.make CMakeFiles/PmtData_static.dir/PmtData.cpp.o
.PHONY : PmtData.cpp.o

PmtData.i: PmtData.cpp.i
.PHONY : PmtData.i

# target to preprocess a source file
PmtData.cpp.i:
	$(MAKE) -f CMakeFiles/PmtData_static.dir/build.make CMakeFiles/PmtData_static.dir/PmtData.cpp.i
.PHONY : PmtData.cpp.i

PmtData.s: PmtData.cpp.s
.PHONY : PmtData.s

# target to generate assembly for a file
PmtData.cpp.s:
	$(MAKE) -f CMakeFiles/PmtData_static.dir/build.make CMakeFiles/PmtData_static.dir/PmtData.cpp.s
.PHONY : PmtData.cpp.s

RawData.o: RawData.cpp.o
.PHONY : RawData.o

# target to build an object file
RawData.cpp.o:
	$(MAKE) -f CMakeFiles/PmtData.dir/build.make CMakeFiles/PmtData.dir/RawData.cpp.o
	$(MAKE) -f CMakeFiles/RawData.dir/build.make CMakeFiles/RawData.dir/RawData.cpp.o
	$(MAKE) -f CMakeFiles/RawData_static.dir/build.make CMakeFiles/RawData_static.dir/RawData.cpp.o
.PHONY : RawData.cpp.o

RawData.i: RawData.cpp.i
.PHONY : RawData.i

# target to preprocess a source file
RawData.cpp.i:
	$(MAKE) -f CMakeFiles/PmtData.dir/build.make CMakeFiles/PmtData.dir/RawData.cpp.i
	$(MAKE) -f CMakeFiles/RawData.dir/build.make CMakeFiles/RawData.dir/RawData.cpp.i
	$(MAKE) -f CMakeFiles/RawData_static.dir/build.make CMakeFiles/RawData_static.dir/RawData.cpp.i
.PHONY : RawData.cpp.i

RawData.s: RawData.cpp.s
.PHONY : RawData.s

# target to generate assembly for a file
RawData.cpp.s:
	$(MAKE) -f CMakeFiles/PmtData.dir/build.make CMakeFiles/PmtData.dir/RawData.cpp.s
	$(MAKE) -f CMakeFiles/RawData.dir/build.make CMakeFiles/RawData.dir/RawData.cpp.s
	$(MAKE) -f CMakeFiles/RawData_static.dir/build.make CMakeFiles/RawData_static.dir/RawData.cpp.s
.PHONY : RawData.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... PmtData"
	@echo "... PmtData_static"
	@echo "... RawData"
	@echo "... RawData_static"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PmtData.o"
	@echo "... PmtData.i"
	@echo "... PmtData.s"
	@echo "... RawData.o"
	@echo "... RawData.i"
	@echo "... RawData.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

